### ISSUE TITLE
update unilemma app

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank-shiny#7]
Since we are putting in some work on the unilemma mapping, we should refresh the shiny app:
- [x] we only cover WG right now, we should add WS coverage for produces (perhaps by stitching together data from both forms)
- [x] dropdown menu doesn't cover all unilemmas because there are too many
- [x] need to recache data
- [x] probably should add some description of what the unilemmas are to the documentation
- [x] could tweak the smoothing functions to be logistic rather than loess so it's less squiggly

**Comment by mikabr** [comment]
remaining points separated into their own issues
